version: '3.4'

services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_DATABASE: 'clockin'
      MYSQL_USER: 'clockin_admin'
      MYSQL_PASSWORD: 'clockin'
    volumes:
      - ./data/mariadb:/docker-entrypoint-initdb.d
    ports:
      - "33006:3306"

  frontend:
    build:
      context: ./clockin_frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    container_name: vue_frontend
    volumes:
      - ./clockin_frontend:/usr/src/app/clockin_frontend
    depends_on:
      - db

  clockin:
     build:
       context: ./clockin_backend
       dockerfile: Dockerfile
     depends_on:
       - db
     ports:
       - "8886:8080"

  mailhog:
     image: mailhog/mailhog:latest
     ports:
       - "8025:8025"
       - "1025:1025"